/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Helpers for the virt io-pgtable format
 */
#ifndef IO_PGTABLE_VIRT_H_
#define IO_PGTABLE_VIRT_H_

#define VIRT_PGTABLE_TABLE_SIZE		0x1000
#define VIRT_PGTABLE_PTE_SIZE		8
#define VIRT_PGTABLE_NUM_PTES							\
	(VIRT_PGTABLE_TABLE_SIZE / VIRT_PGTABLE_PTE_SIZE)
#define VIRT_PGTABLE_BITS_PER_LEVEL	9

#define VIRT_PGTABLE_VA_BITS		48
#define VIRT_PGTABLE_PA_BITS		52
#define VIRT_PGTABLE_GRANULE_SHIFT	12
#define VIRT_PGTABLE_GRANULE		(1ULL << VIRT_PGTABLE_GRANULE_SHIFT)
#define VIRT_PGTABLE_LAST_LEVEL							\
	(((VIRT_PGTABLE_VA_BITS - VIRT_PGTABLE_GRANULE_SHIFT) /			\
	  VIRT_PGTABLE_BITS_PER_LEVEL) - 1)

#define VIRT_PGTABLE_IDX_MASK		((1 << VIRT_PGTABLE_BITS_PER_LEVEL) - 1)
#define VIRT_PGTABLE_IDX_SHIFT(lvl)						\
	((VIRT_PGTABLE_LAST_LEVEL - (lvl)) * VIRT_PGTABLE_BITS_PER_LEVEL +	\
	 VIRT_PGTABLE_GRANULE_SHIFT)

#define VIRT_PGTABLE_PTE_VALID		(1ULL << 0)
#define VIRT_PGTABLE_PTE_TABLE		(1ULL << 1)
#define VIRT_PGTABLE_PTE_READ		(1ULL << 2)
#define VIRT_PGTABLE_PTE_WRITE		(1ULL << 3)
#define VIRT_PGTABLE_PTE_PFN_MASK(lvl)	GENMASK(VIRT_PGTABLE_PA_BITS - 1,	\
						VIRT_PGTABLE_IDX_SHIFT(lvl))
#define VIRT_PGTABLE_PAGE_SIZE(lvl)	(1ULL << VIRT_PGTABLE_IDX_SHIFT(lvl))

#define VIRT_PGTABLE_IDX(iova, lvl) \
	(((iova) >> VIRT_PGTABLE_IDX_SHIFT(lvl)) & VIRT_PGTABLE_IDX_MASK)

typedef u64 viopte_t;

#endif /* IO_PGTABLE_VIRT_H_ */
