# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_VIRTIO_IOMMU) += virtio-iommu.o
obj-$(CONFIG_VIRTIO_IOMMU_TOPOLOGY) += topology.o
obj-$(CONFIG_VIRTIO_IOMMU_TOPOLOGY_HELPERS) += topology-helpers.o
obj-$(CONFIG_ACPI_VIOT) += viot.o
